name: Automated image builds
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ubuntu-image dependencies
        run: |
          sudo apt install -y gdisk qemu-user-static wget
          sudo snap install --classic --channel=latest/edge ubuntu-image

      - name: Fetch submarine
        run: wget -P gadget https://files.tobhe.de/ubuntu/submarine-a64.kpart

      - name: Build desktop
        run: |
           sed -i 's/oracular/noble/g' chromebook-corsola-desktop.yaml
           sudo ubuntu-image --verbose classic chromebook-corsola-desktop.yaml
           sudo sgdisk -A 1:or:11f000000000000 *.img || true

      - name: Upload images
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ubuntu-preinstalled-desktop-arm64-corsola
          path: "*.img"

      - uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
          path: /tmp/ubuntu-image-*/chroot/debootstrap/debootstrap.log
